[package]
name = "qmk-callback"
version = "0.1.0"
edition = "2024"

[dependencies]
qmk-callback-parsing = { path = "../qmk_callback_parsing" }
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = { version = "2.0.100", features = ["full"] }
glob = "0.3.2"
