[package]
name = "include-image"
version = "0.1.0"
edition = "2024"

[dependencies]
include-image-macro = { path = "../include_image_macro" }
include-image-structs = { path = "../include_image_structs" }
