[package]
name = "incim_testing"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
include_image = { path = "../include_image" }
include_image_structs = { path = "../include_image_structs" }
