[workspace]
resolver = "2"
members = [
    "crates/include_image_macro",
    "crates/include_image_structs",
    "crates/include_image",
    "crates/keymap",
    "crates/qmk",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
