TARGET=thumbv6m-none-eabi

build: src/*.rs Cargo.toml build.rs
	cargo rustc --lib --release --target=$(TARGET) \
		-- \
		--emit=obj \
		--codegen opt-level=3 \
		--codegen panic=abort \
		-O
	ln -sf $$(find ./target/$(TARGET)/release/deps/keymap-*.o -printf '%T+ %p\n' | sort -r | head -n 1 | awk '{print $$2}') \
		rust_keymap.o
macro-expand:
	rustc -Z unstable-options --pretty expanded src/keymap.rs
rustc-build:
	rustc --emit=obj \
		--target=$(TARGET) \
		--codegen opt-level=3 \
		--codegen panic=abort \
		src/keymap.rs
dump-keymap-data:
	arm-none-eabi-objdump -s -j .rodata.keymaps  rust_keymap.o
deps:
	rustup target add $(TARGET)
clean:
	cargo clean
	-rm -f rust_keymap.o
