[package]
name = "qmk-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.97"
cfg-if = "1.0.0"
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = { version = "2.0.100", features = ["full"] }
qmk-callback-parsing = { path = "../qmk_callback_parsing" }
